services:
  springboot:
    build:
      context: .  # set the build context to the current directory
      dockerfile: Dockerfile
    container_name: tiny_admin
    volumes:
      - ~/.m2/repository:/root/.m2/repository
    working_dir: /usr/src/app
    command: java -jar tiny-admin-starter.jar
    ports:
      - "9000:8080"
      - "443:443"
    networks:
      - my_network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always

networks:
  my_network:
    name: my_network
