spring:
  server:
    port: 8080
  profiles:
    active: dev
  config:
    import: classpath:.env.local[.properties]
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms