spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  server:
    port: 8080
  profiles:
    active: dev
  config:
    import: classpath:.env.local[.properties]
  cache:
    type: redis

  redisson:
    #  单机模式：https://developer.aliyun.com/article/1430674
    host: ${REDIS_HOST}
    port: 6379
    # 密码
    password: ${REDIS_PASSWORD}
    redis:
      time-to-live: 3600s
    #如果指定了key前缀就用我们指定的前缀，如果没有就默认使用缓存的名字（value）作为前缀，最好不指定前缀
      key-prefix: tiny-admin
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  datasource:
    url: jdbc:mysql://${MYSQL_URL}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

mybatis-plus:
  configuration:
    cache-enabled: true

constant:
  redis-users-token-map-key: tiny-admin-users-token-map

