spring:
  config:
    import: classpath:.env.dev[.properties]
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  server:
    port: 8080
  cache:
    type: redis

  redisson:
    singleServerConfig:
      keyPrefix: tiny_admin

  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 5000
            # Enable reconnect settings for Lettuce
        cluster:
          max-redirects: 3           # Number of times Lettuce will try to reconnect to other nodes
          reconnect-timeout: 10000   # How long to wait for the cluster reconnect before giving up
        shutdown-timeout: 10000

  datasource:
    url: jdbc:mysql://${MYSQL_URL}?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

mybatis-plus:
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

constant:
  redis-users-token-map-key: tiny-admin-users-token-map
security:
  white-url-list:
    - /login
    - /logout
    - /error
    - /actuator/**
    - /v2/api-docs
    - /swagger-ui.html
    - /swagger-resources/**
    - /webjars/**
    - websocket/**
    - /xrebel

firebase.bucket-name:
  tiny-blog-1a77f.appspot.com
firebase.image-url:
  https://storage.googleapis.com/${firebase.bucket-name}/%s